# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20190123_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='merchant',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tube.Merchant'),
        ),
    ]
