# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_video_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['first_name']},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
