# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_auto_20190123_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='merchant',
        ),
    ]
