# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_video_merchant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
