# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_merchant_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
