# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
