# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_auto_20190124_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtubeMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='post',
            new_name='description',
        ),
    ]
