# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0013_auto_20190126_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
