# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-26 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0015_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
